In [0]:
import numpy as np

In [0]:
#1. Create a 3x3 matrix array with values ranging from 2 to 10.

data = np.array([[2, 3, 4],
                  [5, 6, 7],
                  [8, 9, 10]])
data.shape

Out[4]: (3, 3)

In [0]:
"""2. Create a numpy array having user input values and convert the integer type to the float type 
of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]"""

arr=np.array([1,2,3,4])
print(arr)
print(arr.dtype)
arr=arr.astype('float64')
print(arr.dtype)
print(arr)

[1 2 3 4]
int64
float64
[1. 2. 3. 4.]


In [0]:
"""3. Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]"""


arr=np.array([10,20,30])
list1=[40,50,60,70,80,90]
arr=np.append(arr,list1)
arr

Out[6]: array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [0]:
"""4. Create two numpy arrays and add the elements of both the arrays and store the result in 
sumArray."""

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
sumArray=arr1+arr2
sumArray

Out[7]: array([ 6,  8, 10, 12])

In [0]:
"""5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array."""


array1=np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(array1[0])
print(array1[-1])

[10 20 30]
[70 80 90]


In [0]:
"""1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]"""


def solve(size,value):
    arr=np.full(size, value)
    return arr


solve((3,3),5)

Out[9]: array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [0]:
#2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.
def array_sum(arr1,arr2):
    sum=arr1+arr2
    return sum
array_sum(np.array([1,2,3,4]),np.array([5,6,7,8]))

Out[10]: array([ 6,  8, 10, 12])

In [0]:
"""3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M. The method should return the top-left N X M sub matrix e.g:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
top_left_sub_matrix (matrix, 2, 2) -> should return:
 [
 [1, 2]
 [4, 5]
 ]"""

def top_left_sub_matrix(matrix,X,Y):
    return (matrix[:X,:Y])



matrix=np.arange(1,10).reshape(3,3)
print(matrix)
top_left_sub_matrix(matrix,2,2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Out[21]: array([[1, 2],
       [4, 5]])

In [0]:
"""4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]"""


def sub_matrix(matrix,X,Y):
    return (matrix[1:3,1:3])

matrix=np.arange(1,10).reshape(3,3)
print(matrix)
sub_matrix(matrix,1,1)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


In [0]:
"""5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method 
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's 
standard deviation as values:
 [1, 1, 1]
solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0}"""


def mean_stddev(arr):
    l1=["mean","std_dev"]
    d={}
    x=np.mean(arr)
    y=np.std(arr)
    l2=[x,y]
    for i in range(len(l1)):
        d[l1[i]]=l2[i]
    return d


arr=np.array([1,1,1])
mean_stddev(arr)

Out[23]: {'mean': 1.0, 'std_dev': 0.0}